# Generated by Django 3.2.7 on 2021-11-27 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0002_auto_20211125_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shpping',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo'),
            preserve_default=False,
        ),
    ]
